# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f2683da3653da02d6231815a93bd9ee07fbeb5d064534c3b732f1d8b1190965d737015eb89c4e7965b97d04d65bc800d482fd229573e9951f219e23a50857b6

test:
  secret_key_base: f43b3be605b7d59ac9a1608614849639301c669e513234cd4a80959166e13ef0806751afdca5b4df86852abe00668a277fd26f53242d0948914e97eba89bf0a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
